#!/usr/bin/env bash
#the script is used to run nginx from nginx user
# change the ownership of the nginx directory to group ownership
sudo chown root:nginx /etc/nginx/nginx.conf
sudo chmod 744 /etc/nginx/nginx.conf

# using sed to replace the default port 80 with 8080
# change nginx user to nginx
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# restart nginx
sudo systemctl stop nginx
sudo systemctl start nginx
